### ISSUE TITLE
Profiler show text report not working

### ISSUE THREAD

**Issue by BackOrder** [shoes/shoes3#390] opened 2017-11-23 20:43 UTC
**Show text report** hangs Shoes on FreeBSD.

**Comment by ccoupe** [comment] 2017-11-24 02:40
BSD does produce unexpected errors. Can you bring up the Shoes log/console - there maybe an error on it. Or small script to call shoes.terminal which is what the text profiler uses.

**Comment by BackOrder** [comment] 2017-11-24 15:54
Opening `Shoes.terminal` prevents freezing but it will not display anything in an actual terminal nor in Shoes.terminal window. The profiler window shows a button to go back to **GUI Display**, clicking working.

Opening the profiler from cobbler, running and show text report leads to the following error:

```ruby
Error in <unknown> line 0 | 2017-11-24 10:48:52 -0500
no implicit conversion of nil into String
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:330:in `basename'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:330:in `block in textscreen'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:326:in `stack'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:326:in `textscreen'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:303:in `call'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:303:in `visit'
/usr/home/ian/.shoes/walkabout/lib/shoes/profiler.rb:303:in `block (3 levels) in graphscreen'
```

**Comment by ccoupe** [comment] 2017-11-25 03:21
This does seem to be unique to bsd. Confirmed that it fails. OK on linux. A quick scan of the ruby only provides a suspicion that maybe visit()  has broken again . Only a guess.

**Comment by ccoupe** [comment] 2017-11-27 02:26
I have a workaround since it's a very strange bug. Output to the launch terminal. Might as well output to a file while I'm at it. Could be helpful for #389 test archiving. 
![profiler](https://user-images.githubusercontent.com/222691/33247902-cf310302-d2de-11e7-96aa-7b1d207ee2c9.png)

There is a Windows exe [beta](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.5-gtk3-32.exe) at the usual place. @BackOrder will have to build minbsd (where it did the mods).

**Comment by BackOrder** [comment] 2017-11-27 03:00
This is great work @ccoupe. It will certainly be useful.

**Comment by ccoupe** [comment] 2018-01-13 04:11
Closing. Not perfectly fixed but freebsd only bugs have low priority.

**Closed by ccoupe** 2018-01-13 04:11 UTC
Labels: FreeBSD
