### ISSUE TITLE
Shoes high CPU utilization 

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#387] opened 2017-11-16 18:10 UTC
Hey everyone,

Just noticed that when Shoes app is launched CPU goes 40% higher and stays there.
It happens on both my apps and Shoes manual too.
CPU util with no shoes app - ~20%
CPU util with shoes app active (just started no clicking or animation) ~60-70%

Why is this happening? Here is the app window that is working

![image](https://user-images.githubusercontent.com/12410314/32907726-b8b86a2a-cb09-11e7-8b33-6026cc7c66c5.png)

I am using the latest stable verssion 3.3.4 r3079.
This happens even when the manual is open.
The system (windows 10) specifics that experience this issue is :
![image](https://user-images.githubusercontent.com/12410314/32907804-010e63ec-cb0a-11e7-8db9-ffc5b9ff83ec.png) with HDD

I will test on a more powerful hardware tomorrow.

**Comment by BackOrder** [comment] 2017-11-17 01:00
This might need more testing because CPU usage is not warrant of a problem. Each operating system has its own strategy to deal with the foreground application. Windows may simply allocate more CPU because it is in foreground and no other application is needing CPU.

You might want to try to minimize it first and see whether it goes down or not. You might also want to try with other applications running and see whether it interferes or not.

Was the previous version of Shoes a problem?

**Comment by BackOrder** [comment] 2017-11-17 01:06
> CPU util with shoes app active (just started no clicking or animation) ~60-70%

Windows disk I/O isn't that great by the way. That could explain the peek. :)

If it's a laptop, it's probably a 5400 RPM HDD. Terribly slow. 

You might want to check starting other apps and compare.

I can't even test on my computers. They ain't waiting for no one with their RAIDs and SSDs.

**Comment by dredknight** [comment] 2017-11-17 11:29
> Was the previous version of Shoes a problem?

I was on 3.3.3 and after the issue was noticed I decided to upgrade. 

It is not laptop it is standard tower pc. HDD is 7200 but it is old (~5 years).
I tested on a cutting edge hardware (intel core i7 at 2.5GHz, 8GB DDR3) it works  normally.

When I am back at the other machine I will move the app on the SSD and see if there is difference. It is possible that the time has come for a new HDD.

**Comment by BackOrder** [comment] 2017-11-17 11:39
> When I am back at the other machine I will move the app on the SSD and see if there is difference. It is possible that the time has come for a new HDD.

This is what I suspect. You might have bad blocks on this old HDD causing the OS to read more frequently. Once again Windows is pretty bad with such things.

**Comment by dredknight** [comment] 2017-11-17 19:06
Experiment 2. 
Old config + SSD = same CPU result.
Moreover when the app is minimized the CPU is still consumed.
![image](https://user-images.githubusercontent.com/12410314/32964228-2e73a532-cbdb-11e7-8882-3b6b549e6d4c.png)
That value was about 5% before shoes was launched.

**Comment by dredknight** [comment] 2017-11-17 19:35
I do not have a clue what is going on. Unless I get some revelation the next few days I will be closing this one.

**Comment by BackOrder** [comment] 2017-11-17 19:40
You might want to leave this issue open. It needs further investigation.

**Comment by ccoupe** [comment] 2017-11-17 20:00
You try the Shoes profiling ability. - Instructions are somewhere on the wiki.

**Comment by BackOrder** [comment] 2017-11-17 20:26
Reference: https://github.com/shoes/shoes3/wiki/Profiling

**Comment by dredknight** [comment] 2017-11-17 21:08
Thanks!
Launched it, waited 10 seconds and stop it. No any user actions were done whatsoever. Here is the result.

I read the article but I do not know how to interpret the values, etc. is the high too high or just normal?
Note: I skipped some near zero rows.

**By call count**
![image](https://user-images.githubusercontent.com/12410314/32968960-d01fd968-cbeb-11e7-8807-5d2287b4e749.png)
![image](https://user-images.githubusercontent.com/12410314/32968966-d790b96a-cbeb-11e7-9342-be9fbc827014.png)

**By method time**
![image](https://user-images.githubusercontent.com/12410314/32969003-0044e5d4-cbec-11e7-9d94-4d0baafc5a12.png)
![image](https://user-images.githubusercontent.com/12410314/32969017-0deeb1c4-cbec-11e7-80ad-a15759f71057.png)

**Comment by ccoupe** [comment] 2017-11-18 02:37
Looks like it draws a lot, but we knew that.  It doesn't look unusual to me so it's not likely be your program, unless there was a lot of paging and with 8GB, probably not.  On my VM,  win7, idle shoes splash screen can get to 100% of one cpu core.  Not good.

I did change Windows polling of events in 3.3.4 (or 3.3.3 ?) to improve download speed and that may be the cause. I can test that.

**Comment by ccoupe** [comment] 2017-11-18 06:11
@dredknight , new [beta 3.3.5](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.5-gtk3-32.exe
) for windows should reduce your cpu consumption.  Built from master so none of that event drama. Let me know what it does for you.

**Comment by dredknight** [comment] 2017-11-18 08:58
@ccoupe what sorcery is this? It works!

When idle (maximized or minimized) CPU usage is 0%. It gets triggered only when computing events.

**Comment by ccoupe** [comment] 2018-01-13 03:37
Closing.

**Closed by ccoupe** 2018-01-13 03:37 UTC
Labels: Windows
